using System;

namespace FCSAmerica.Transact.ServiceModels
{
    public class IncomingWireDetailServiceModel
    {
        public int IncomingWireId { get; set; }
        public int BankFileHistoryId { get; set; }
        public string Detail { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime UpdatedOn { get; set; }
        public string AcknowledgementTrash1 { get; set; }
        public string FormatVersion1100 { get; set; }
        public string TestProductionCode { get; set; }
        public string MsgDuplicationCode1100 { get; set; }
        public string MsgStatusInd { get; set; }
        public string AcceptanceDate { get; set; }
        public string AcceptanceTime { get; set; }
        public string AcceptanceApplId { get; set; }
        public string OutputCycleDate { get; set; }
        public string OutputDestinationId { get; set; }
        public string OutputDate { get; set; }
        public string OutputTime { get; set; }
        public string OutputSequenceNumber { get; set; }
        public string OutputFrbApplId { get; set; }
        public string ErrorCategory1130 { get; set; }
        public string ErrorCode1130 { get; set; }
        public string ErrorDescription1130 { get; set; }
        public string ErrorCategory1300 { get; set; }
        public string ErrorCode1300 { get; set; }
        public string ErrorDescription1300 { get; set; }
        public string FormatVersion1500 { get; set; }
        public string UrcData { get; set; }
        public string TestProdCode { get; set; }
        public string MsgDuplicationCode1500 { get; set; }
        public string Filler { get; set; }
        public string TypeCode { get; set; }
        public string SubtypeCode { get; set; }
        public string InputCycleDate { get; set; }
        public string InputSource { get; set; }
        public string InputSequenceNumber { get; set; }
        public decimal? Amount { get; set; }
        public string AdjustmentDate { get; set; }
        public string AdjustmentReason { get; set; }
        public string SenderDiNumber { get; set; }
        public string SenderShortName { get; set; }
        public string SenderReference { get; set; }
        public string ReceiverDiNumber { get; set; }
        public string ReceiverShortName { get; set; }
        public string PrevInputCycleDate { get; set; }
        public string PrevInputSourceId { get; set; }
        public string PrevInputSeqNr { get; set; }
        public string BusinessFunctionCode { get; set; }
        public string DetailsOfCharges { get; set; }
        public string IntermediaryFiIdentifier { get; set; }
        public string IntermediaryFiName { get; set; }
        public string IntermediaryFiAddressLine1 { get; set; }
        public string IntermediaryFiAddressLine2 { get; set; }
        public string IntermediaryFiAddressLine3 { get; set; }
        public string BeneficiaryFiIdentifier { get; set; }
        public string BeneficiaryFiName { get; set; }
        public string BeneficiaryFiAddressLine1 { get; set; }
        public string BeneficiaryFiAddressLine2 { get; set; }
        public string BeneficiaryFiAddressLine3 { get; set; }
        public string BeneficiaryIdentifier { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAddressLine1 { get; set; }
        public string BeneficiaryAddressLine2 { get; set; }
        public string BeneficiaryAddressLine3 { get; set; }
        public string BeneficiaryRef { get; set; }
        public string DrwDebitAcctIdCode { get; set; }
        public string DrwDebitAcctIdentifier { get; set; }
        public string DrwDebitAcctName { get; set; }
        public string DrwDebitAcctAddressLine1 { get; set; }
        public string DrwDebitAcctAddressLine2 { get; set; }
        public string DrwDebitAcctAddressLine3 { get; set; }
        public string OriginatorIdentifier { get; set; }
        public string OriginatorName { get; set; }
        public string OriginatorAddressLine1 { get; set; }
        public string OriginatorAddressLine2 { get; set; }
        public string OriginatorAddressLine3 { get; set; }
        public string OriginatorFiIdentifier { get; set; }
        public string OriginatorFiName { get; set; }
        public string OriginatorFiAddressLine1 { get; set; }
        public string OriginatorFiAddressLine2 { get; set; }
        public string OriginatorFiAddressLine3 { get; set; }
        public string InstructingFiIdentifier { get; set; }
        public string InstructingFiName { get; set; }
        public string InstructingFiAddressLine1 { get; set; }
        public string InstructingFiAddressLine2 { get; set; }
        public string InstructingFiAddressLine3 { get; set; }
        public string DrwCreditAcctNr { get; set; }
        public string OriginatorToBeneficiaryLine1 { get; set; }
        public string OriginatorToBeneficiaryLine2 { get; set; }
        public string OriginatorToBeneficiaryLine3 { get; set; }
        public string OriginatorToBeneficiaryLine4 { get; set; }
        public string ReceiverFiInfoLine1 { get; set; }
        public string ReceiverFiInfoAddition { get; set; }
        public string DrwDebitAcctAdviceCode { get; set; }
        public string DrwDebitAcctAdviceInfoLine1 { get; set; }
        public string DrwDebitAcctAdviceInfoLine { get; set; }
        public string IntermediaryFiInfoLine1 { get; set; }
        public string IntermediaryFiInfoAdditionalLine { get; set; }
        public string IntermediaryFiAdviceCode { get; set; }
        public string IntermediaryFiAdviceInfoLine1 { get; set; }
        public string IntermediaryFiAdviceInfoAdditionalLine1 { get; set; }
        public string BeneficiarysFiInfoLine1 { get; set; }
        public string BeneficiarysFiAdviceInfoAdditionalLine6300 { get; set; }
        public string BeneficiarysFiAdviceLine1 { get; set; }
        public string BeneficiarysFiAdviceInfoLine { get; set; }
        public string BeneficiaryInfoLine1 { get; set; }
        public string BeneficiaryInfoAdditionalLine { get; set; }
        public string BeneficiarysFiAdviceInfoAdditionalLine6310 { get; set; }
        public string BeneficiaryAdviceCode { get; set; }
        public string BeneficiaryAdviceInfoLine { get; set; }
        public string BeneficiaryAdviceInfoAdditionalLine { get; set; }
        public string MethodOfPaymentCode { get; set; }
        public string MethodOfPaymentInfoLine { get; set; }
        public string FiToFiFreeTextLine { get; set; }
        public string FreeTextInfoLine1 { get; set; }
        public string FreeTextInfoAdditionalLine { get; set; }
    }
}
