//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionWorkQueue
    {
        public int ExceptionWorkQueue_ID { get; set; }
        public int MaterialReceiptEvent_ID { get; set; }
        public string ExceptionCode { get; set; }
        public string Operator_ID { get; set; }
        public string AddiitonalInfo { get; set; }
    
        public virtual ExceptionType ExceptionType { get; set; }
        public virtual MaterialReceiptEvent MaterialReceiptEvent { get; set; }
    }
}
