//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialReceiptEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialReceiptEvent()
        {
            this.ExceptionWorkQueue = new HashSet<ExceptionWorkQueue>();
        }
    
        public int MaterialReceiptEvent_ID { get; set; }
        public int VendorDeliveryMaterial_ID { get; set; }
        public string Operator_ID { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string Batch { get; set; }
        public string Lot { get; set; }
        public Nullable<decimal> QtyEntered { get; set; }
        public string UOM_Entered { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public Nullable<decimal> WeightReceived { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ProblemCode { get; set; }
        public string ProductConditionCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionWorkQueue> ExceptionWorkQueue { get; set; }
        public virtual VendorDeliveryMaterial VendorDeliveryMaterial { get; set; }
        public virtual ProblemType ProblemType { get; set; }
    }
}
