//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckInspection
    {
        public int VendorDelivery_ID { get; set; }
        public string Comments { get; set; }
        public string ConditionCode { get; set; }
        public string TruckCode { get; set; }
        public byte InspectionPass { get; set; }
        public string Operator_ID { get; set; }
        public decimal Temperature { get; set; }
    
        public virtual TruckCondition TruckCondition { get; set; }
        public virtual TruckType TruckType { get; set; }
        public virtual VendorDelivery VendorDelivery { get; set; }
    }
}
