//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LSG_AIDCEntities : DbContext
    {
        public LSG_AIDCEntities()
            : base("name=LSG_AIDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeliveryStatus> DeliveryStatus { get; set; }
        public virtual DbSet<ExceptionType> ExceptionType { get; set; }
        public virtual DbSet<ExceptionWorkQueue> ExceptionWorkQueue { get; set; }
        public virtual DbSet<ExpirationDateType> ExpirationDateType { get; set; }
        public virtual DbSet<MaterialReceiptEvent> MaterialReceiptEvent { get; set; }
        public virtual DbSet<NLINK_ActivityProgress> NLINK_ActivityProgress { get; set; }
        public virtual DbSet<NLINK_ActivityStatus> NLINK_ActivityStatus { get; set; }
        public virtual DbSet<NLINK_PostReceipt> NLINK_PostReceipt { get; set; }
        public virtual DbSet<NLINK_ProcessActivityType> NLINK_ProcessActivityType { get; set; }
        public virtual DbSet<NLINK_ProgressPhaseType> NLINK_ProgressPhaseType { get; set; }
        public virtual DbSet<PHF_CodeMap> PHF_CodeMap { get; set; }
        public virtual DbSet<PO_PhaseStatus> PO_PhaseStatus { get; set; }
        public virtual DbSet<PO_Worklist> PO_Worklist { get; set; }
        public virtual DbSet<PO_WorkListItem> PO_WorkListItem { get; set; }
        public virtual DbSet<ProbeMaster> ProbeMaster { get; set; }
        public virtual DbSet<ProbeSlave> ProbeSlave { get; set; }
        public virtual DbSet<ProblemType> ProblemType { get; set; }
        public virtual DbSet<TempValidationType> TempValidationType { get; set; }
        public virtual DbSet<TruckCondition> TruckCondition { get; set; }
        public virtual DbSet<TruckInspection> TruckInspection { get; set; }
        public virtual DbSet<TruckType> TruckType { get; set; }
        public virtual DbSet<VendorDelivery> VendorDelivery { get; set; }
        public virtual DbSet<VendorDeliveryMaterial> VendorDeliveryMaterial { get; set; }
        public virtual DbSet<Books> Books { get; set; }
    
        public virtual int NLINKCreateActivityProgress(string in_ProcessPhaseCode, string in_ActivityCode, string in_ActivityStatus, ObjectParameter new_identity)
        {
            var in_ProcessPhaseCodeParameter = in_ProcessPhaseCode != null ?
                new ObjectParameter("in_ProcessPhaseCode", in_ProcessPhaseCode) :
                new ObjectParameter("in_ProcessPhaseCode", typeof(string));
    
            var in_ActivityCodeParameter = in_ActivityCode != null ?
                new ObjectParameter("in_ActivityCode", in_ActivityCode) :
                new ObjectParameter("in_ActivityCode", typeof(string));
    
            var in_ActivityStatusParameter = in_ActivityStatus != null ?
                new ObjectParameter("in_ActivityStatus", in_ActivityStatus) :
                new ObjectParameter("in_ActivityStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreateActivityProgress", in_ProcessPhaseCodeParameter, in_ActivityCodeParameter, in_ActivityStatusParameter, new_identity);
        }
    
        public virtual int NLINKCreateMaterialReceiptEvent(Nullable<int> in_VendorDeliveryMaterial_ID, string in_ProblemCode, string in_ProductConditionCode, ObjectParameter new_identity)
        {
            var in_VendorDeliveryMaterial_IDParameter = in_VendorDeliveryMaterial_ID.HasValue ?
                new ObjectParameter("in_VendorDeliveryMaterial_ID", in_VendorDeliveryMaterial_ID) :
                new ObjectParameter("in_VendorDeliveryMaterial_ID", typeof(int));
    
            var in_ProblemCodeParameter = in_ProblemCode != null ?
                new ObjectParameter("in_ProblemCode", in_ProblemCode) :
                new ObjectParameter("in_ProblemCode", typeof(string));
    
            var in_ProductConditionCodeParameter = in_ProductConditionCode != null ?
                new ObjectParameter("in_ProductConditionCode", in_ProductConditionCode) :
                new ObjectParameter("in_ProductConditionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreateMaterialReceiptEvent", in_VendorDeliveryMaterial_IDParameter, in_ProblemCodeParameter, in_ProductConditionCodeParameter, new_identity);
        }
    
        public virtual int NLINKCreatePO_Worklist(Nullable<int> in_VendorDelivery_ID, string in_PO_PhaseStatus, ObjectParameter new_identity)
        {
            var in_VendorDelivery_IDParameter = in_VendorDelivery_ID.HasValue ?
                new ObjectParameter("in_VendorDelivery_ID", in_VendorDelivery_ID) :
                new ObjectParameter("in_VendorDelivery_ID", typeof(int));
    
            var in_PO_PhaseStatusParameter = in_PO_PhaseStatus != null ?
                new ObjectParameter("in_PO_PhaseStatus", in_PO_PhaseStatus) :
                new ObjectParameter("in_PO_PhaseStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreatePO_Worklist", in_VendorDelivery_IDParameter, in_PO_PhaseStatusParameter, new_identity);
        }
    
        public virtual int NLINKCreatePO_WorklistItem(Nullable<int> in_PO_WorkList_ID, Nullable<int> in_VendorDeliveryMaterial_ID, ObjectParameter new_identity)
        {
            var in_PO_WorkList_IDParameter = in_PO_WorkList_ID.HasValue ?
                new ObjectParameter("in_PO_WorkList_ID", in_PO_WorkList_ID) :
                new ObjectParameter("in_PO_WorkList_ID", typeof(int));
    
            var in_VendorDeliveryMaterial_IDParameter = in_VendorDeliveryMaterial_ID.HasValue ?
                new ObjectParameter("in_VendorDeliveryMaterial_ID", in_VendorDeliveryMaterial_ID) :
                new ObjectParameter("in_VendorDeliveryMaterial_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreatePO_WorklistItem", in_PO_WorkList_IDParameter, in_VendorDeliveryMaterial_IDParameter, new_identity);
        }
    
        public virtual int NLINKCreateVendorDelivery(string in_DeliveryStatus, string in_SAP_Vendor_ID, ObjectParameter new_identity)
        {
            var in_DeliveryStatusParameter = in_DeliveryStatus != null ?
                new ObjectParameter("in_DeliveryStatus", in_DeliveryStatus) :
                new ObjectParameter("in_DeliveryStatus", typeof(string));
    
            var in_SAP_Vendor_IDParameter = in_SAP_Vendor_ID != null ?
                new ObjectParameter("in_SAP_Vendor_ID", in_SAP_Vendor_ID) :
                new ObjectParameter("in_SAP_Vendor_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreateVendorDelivery", in_DeliveryStatusParameter, in_SAP_Vendor_IDParameter, new_identity);
        }
    
        public virtual int NLINKCreateVendorDeliveryMaterial(Nullable<int> in_VendorDelivery_ID, ObjectParameter new_identity)
        {
            var in_VendorDelivery_IDParameter = in_VendorDelivery_ID.HasValue ?
                new ObjectParameter("in_VendorDelivery_ID", in_VendorDelivery_ID) :
                new ObjectParameter("in_VendorDelivery_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NLINKCreateVendorDeliveryMaterial", in_VendorDelivery_IDParameter, new_identity);
        }
    
        public virtual ObjectResult<RCV_REVIEW_RECEIPT_GRID_Result> RCV_REVIEW_RECEIPT_GRID(string vendorDelivery_ID)
        {
            var vendorDelivery_IDParameter = vendorDelivery_ID != null ?
                new ObjectParameter("VendorDelivery_ID", vendorDelivery_ID) :
                new ObjectParameter("VendorDelivery_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RCV_REVIEW_RECEIPT_GRID_Result>("RCV_REVIEW_RECEIPT_GRID", vendorDelivery_IDParameter);
        }
    
        public virtual ObjectResult<GetReceiveReceiptInfo_Result> GetReceiveReceiptInfo(Nullable<int> vendorDeliveryId, string sapPOWorkListId, string vendorDeliveryCode, Nullable<bool> isException)
        {
            var vendorDeliveryIdParameter = vendorDeliveryId.HasValue ?
                new ObjectParameter("VendorDeliveryId", vendorDeliveryId) :
                new ObjectParameter("VendorDeliveryId", typeof(int));
    
            var sapPOWorkListIdParameter = sapPOWorkListId != null ?
                new ObjectParameter("SapPOWorkListId", sapPOWorkListId) :
                new ObjectParameter("SapPOWorkListId", typeof(string));
    
            var vendorDeliveryCodeParameter = vendorDeliveryCode != null ?
                new ObjectParameter("VendorDeliveryCode", vendorDeliveryCode) :
                new ObjectParameter("VendorDeliveryCode", typeof(string));
    
            var isExceptionParameter = isException.HasValue ?
                new ObjectParameter("IsException", isException) :
                new ObjectParameter("IsException", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReceiveReceiptInfo_Result>("GetReceiveReceiptInfo", vendorDeliveryIdParameter, sapPOWorkListIdParameter, vendorDeliveryCodeParameter, isExceptionParameter);
        }
    
        public virtual ObjectResult<string> GetListOfPOs(Nullable<int> vendorDeliveryId)
        {
            var vendorDeliveryIdParameter = vendorDeliveryId.HasValue ?
                new ObjectParameter("VendorDeliveryId", vendorDeliveryId) :
                new ObjectParameter("VendorDeliveryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetListOfPOs", vendorDeliveryIdParameter);
        }
    }
}
