//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHF_CodeMap
    {
        public string SAP_PHF_Code { get; set; }
        public string TempValidationCode { get; set; }
        public string ExpirationDateCode { get; set; }
    
        public virtual ExpirationDateType ExpirationDateType { get; set; }
        public virtual TempValidationType TempValidationType { get; set; }
    }
}
