//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_WorkListItem
    {
        public int PO_WorklistItem_ID { get; set; }
        public int PO_WorkList_ID { get; set; }
        public int VendorDeliveryMaterial_ID { get; set; }
        public byte IsItemComplete { get; set; }
        public byte IsKLine { get; set; }
        public Nullable<decimal> QtyExpected { get; set; }
        public Nullable<decimal> WeightExpected { get; set; }
        public Nullable<decimal> QtyNormalDist { get; set; }
        public Nullable<decimal> WeightNormalDist { get; set; }
        public Nullable<decimal> QtyDamageDist { get; set; }
        public Nullable<decimal> QtyOffTempDist { get; set; }
        public Nullable<decimal> WeightOffTempDist { get; set; }
        public string SAP_LineItem_ID { get; set; }
        public string SAP_Plant { get; set; }
        public string SAP_Location { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public string GoodsMovementDoc { get; set; }
        public string GoodsMovementYear { get; set; }
        public string GoodsMovementLine { get; set; }
        public Nullable<byte> IsItemPosted { get; set; }
    
        public virtual PO_Worklist PO_Worklist { get; set; }
        public virtual VendorDeliveryMaterial VendorDeliveryMaterial { get; set; }
    }
}
