//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSG_AIDC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorDeliveryMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorDeliveryMaterial()
        {
            this.MaterialReceiptEvent = new HashSet<MaterialReceiptEvent>();
            this.PO_WorkListItem = new HashSet<PO_WorkListItem>();
        }
    
        public int VendorDeliveryMaterial_ID { get; set; }
        public int VendorDelivery_ID { get; set; }
        public Nullable<decimal> QtyExpected { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public Nullable<decimal> WeightExpected { get; set; }
        public Nullable<decimal> WeightReceived { get; set; }
        public Nullable<byte> IsUnexpectedMaterial { get; set; }
        public string EnteredMaterial_ID { get; set; }
        public string EnteredMaterial_Description { get; set; }
        public string EnteredMaterialUOM { get; set; }
        public string TempValidationCode { get; set; }
        public string ExpirationDateCode { get; set; }
        public string SAP_VendorMaterial_ID { get; set; }
        public string SAP_VendorMaterialDesc { get; set; }
        public string SAP_Material_ID { get; set; }
        public string SAP_Description { get; set; }
        public string SAP_BaseUOM { get; set; }
        public string SAP_OrderUOM { get; set; }
        public string SAP_PHF_Code { get; set; }
        public string SAP_ReligiousDietCode { get; set; }
        public string SAP_AllergenCode { get; set; }
    
        public virtual ExpirationDateType ExpirationDateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialReceiptEvent> MaterialReceiptEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_WorkListItem> PO_WorkListItem { get; set; }
        public virtual TempValidationType TempValidationType { get; set; }
        public virtual VendorDelivery VendorDelivery { get; set; }
    }
}
